Models/ErrorViewModel.cs
namespace MVC_FluentValidation.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/PassengerCreateVM.cs
using MVC_FluentValidation.Entites;

namespace MVC_FluentValidation.Models
{
    public class PassengerCreateVM
    {
        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? TicketNumber { get; set; }

        public Gender? Gender { get; set; }
    }
}

Models/PassengerListVM.cs
using MVC_FluentValidation.Entites;

namespace MVC_FluentValidation.Models
{
    public class PassengerListVM
    {
        public Guid Id { get; set; } = Guid.NewGuid();

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public int TicketNumber { get; set; }

        public Gender Gender { get; set; }
    }
}

Models/PassengerUpdateVM.cs
using MVC_FluentValidation.Entites;

namespace MVC_FluentValidation.Models
{
    public class PassengerUpdateVM
    {
        public Guid Id { get; set; }
        public string? FirstName { get; set; }

        public string? LastName { get; set; }

        public string? TicketNumber { get; set; }

        public Gender? Gender { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_FluentValidation.Models;
using System.Diagnostics;

namespace MVC_FluentValidation.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PassengerController.cs
using Mapster;
using Microsoft.AspNetCore.Mvc;
using MVC_FluentValidation.Entites;
using MVC_FluentValidation.Models;

namespace MVC_FluentValidation.Controllers
{
    public class PassengerController : Controller
    {
        public IActionResult Index()
        {
            if (DataBase.passengers.Count <= 0)
            {
                Passenger passenger = new Passenger()
                {
                    Gender = Gender.Male,
                    FirstName = "Ahmet",
                    LastName = "Cunda",
                    TicketNumber = 101
                };

                Passenger passenger2 = new Passenger()
                {
                    Gender = Gender.Male,
                    FirstName = "Mehmet",
                    LastName = "Aksoy",
                    TicketNumber = 102
                };

                DataBase.passengers.Add(passenger);
                DataBase.passengers.Add(passenger2);
            }
            return View(DataBase.passengers.Adapt<List<PassengerListVM>>());

        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(PassengerCreateVM createVM)
        {
            if(!ModelState.IsValid)
            {
                return View(createVM);
            }

            DataBase.passengers.Add(createVM.Adapt<Passenger>());

            return RedirectToAction("Index");
        }

        public IActionResult Update(Guid id)
        {
            var updateModel = DataBase.passengers.FirstOrDefault(x => x.Id == id);

            if(updateModel != null)
            {
                return View();
            }

            return View(updateModel);
        }

        [HttpPost]
        public IActionResult Update(PassengerUpdateVM model)
        {
            if (ModelState.IsValid)
            {
                var updateModel = DataBase.passengers.FirstOrDefault(x => x.Id == model.Id);
                if (updateModel == null)
                {
                    return View();
                }

                // Verileri güncelle
                updateModel.FirstName = model.FirstName;
                updateModel.LastName = model.LastName;
                updateModel.TicketNumber = Convert.ToInt32(model.TicketNumber);

                return RedirectToAction("Index");
            }

            return View(model);


        }

        public IActionResult Delete (Guid id)
        {
            var deleted = DataBase.passengers.FirstOrDefault(x => x.Id == id);
            if (deleted != null)
            {
                DataBase.passengers.Remove(deleted);
                return RedirectToAction("Index");
            }
            return View();
        }



    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Passenger/Create.cshtml
@model MVC_FluentValidation.Models.PassengerCreateVM

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>PassengerCreateVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketNumber" class="control-label"></label>
                <input asp-for="TicketNumber" class="form-control" />
                <span asp-validation-for="TicketNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control" />
                <option value=""> Select Gender</option>
                @foreach (var item in Enum.GetValues(typeof(Gender)))
                {
                    <option> @item</option>
                }
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/Passenger/Index.cshtml
@model IEnumerable<MVC_FluentValidation.Models.PassengerListVM>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TicketNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Gender)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LastName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TicketNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gender)
            </td>
            <td>
                @Html.ActionLink("Update", "Update", new {  id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

Views/Passenger/Update.cshtml
@model MVC_FluentValidation.Models.PassengerUpdateVM

@{
    ViewData["Title"] = "Update";
}

<h1>Update</h1>

<h4>PassengerUpdateVM</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Update">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TicketNumber" class="control-label"></label>
                <input asp-for="TicketNumber" class="form-control" />
                <span asp-validation-for="TicketNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Gender" class="control-label"></label>
                <select asp-for="Gender" class="form-control" />
                <option value=""> Select Gender</option>
                @foreach (var item in Enum.GetValues(typeof(Gender)))
                {
                    <option> @item</option>
                }
                </select>
                <span asp-validation-for="Gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MVC_FluentValidation</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_FluentValidation.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MVC_FluentValidation</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Passenger" asp-action="Index">Passenger</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MVC_FluentValidation - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>